apiVersion: v1
kind: Namespace
metadata:
  name: taskflow
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: taskflow-staging
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: platform
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: taskflow-production
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: platform
    environment: production
